name: fireauth
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  relative_scale: ^2.0.0
  gradient_widgets: ^0.6.0
  convex_bottom_bar: ^3.0.0
  numberpicker: ^2.1.1
  outline_gradient_button: ^2.0.0+1
  material_design_icons_flutter: ^4.0.5955
  flutter_rating_bar: ^4.0.0
  dash_chat: ^1.1.16
  file_picker: ^4.1.3
  fluttericon: ^2.0.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.2
  provider:
  firebase_core: ^1.7.0
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1
  video_player: ^2.2.5
  cloud_firestore_web: ^2.4.3
  video_compress: ^3.0.0
  path_provider:
  flutter_image_compress:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700